/* ENG 270 — shared workshop engine (same interaction model and scoring hooks as ENG 494) */
function switchTab(id,btn){document.querySelectorAll('.tab-panel').forEach(function(p){p.classList.remove('active');});document.querySelectorAll('.tab-btn').forEach(function(b){b.classList.remove('active');});document.getElementById('tab-'+id).classList.add('active');btn.classList.add('active');}
var MCQ={};
function shuffleQ(q){if(q._o0===undefined){q._o0=q.opts.slice();q._a0=q.ans;}var idx=q._o0.map(function(_,i){return i;});for(var i=idx.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=idx[i];idx[i]=idx[j];idx[j]=t;}q.opts=idx.map(function(k){return q._o0[k];});q.ans=idx.indexOf(q._a0);return q;}
function mount(cid,items){var el=document.getElementById(cid);if(!el)return;MCQ[cid]=items;items.forEach(shuffleQ);el.innerHTML=items.map(function(q,qi){return '<div class="ex-card">'+(q.pre||'')+'<div class="ex-q" style="margin:6px 0 12px;">'+q.q+'</div>'+q.opts.map(function(o,oi){return '<button class="ex-opt" id="'+cid+'-'+qi+'-'+oi+'" onclick="ans(\''+cid+'\','+qi+','+oi+')">'+o+'</button>';}).join('')+'<div class="ex-feedback" id="'+cid+'-fb-'+qi+'"></div></div>';}).join('');}
function ans(cid,qi,ch){var q=MCQ[cid][qi];if(document.getElementById(cid+'-'+qi+'-0').disabled)return;q.opts.forEach(function(_,oi){var b=document.getElementById(cid+'-'+qi+'-'+oi);b.disabled=true;if(oi===q.ans)b.classList.add('correct-ans');else if(oi===ch&&ch!==q.ans)b.classList.add('wrong-ans');});var fb=document.getElementById(cid+'-fb-'+qi);fb.className='ex-feedback show '+(ch===q.ans?'fb-correct':'fb-wrong');fb.innerHTML=q.why;}
var TASKS=[];
function initTasks(){var el=document.getElementById('translate-tasks');if(!el||!TASKS.length)return;el.innerHTML=TASKS.map(function(t,i){return '<div class="ex-card"><div class="ex-num">'+t.title+'</div><div class="excerpt'+(t.rtl?' ar':'')+'">'+t.text+'<span class="cite">— '+t.cite+'</span></div><p style="font-size:13px;color:var(--text-2);margin:8px 0 6px;">'+(t.prompt||'Type your Arabic translation:')+'</p><textarea class="tp-input" id="tp-'+i+'"'+(t.ltr?' style="direction:ltr;text-align:left;"':'')+' placeholder="'+(t.ph||'اكتب ترجمتك هنا…')+'"></textarea><button class="btn btn-primary btn-sm tp-btn" style="background:var(--ac);" onclick="reveal('+i+')">Reveal translator&rsquo;s notes &rarr;</button><div class="tp-reveal" id="tp-rev-'+i+'"><h4>The challenge</h4><div>'+t.challenges+'</div><h4>Recommended strategy</h4><div>'+t.strategy+'</div>'+(t.sample?'<h4>One possible rendering</h4><div class="tp-sample">'+t.sample+'</div><div class="src-note">'+(t.sampleNote||'')+'</div>':'')+'<h4>Check your version</h4><ul class="checklist2">'+t.check.map(function(c){return '<li>'+c+'</li>';}).join('')+'</ul></div></div>';}).join('');}
function reveal(i){document.getElementById('tp-rev-'+i).classList.add('show');}
var AQ=[],aqi=0,aqs=0,aqd=false;
function rAQ(){if(!document.getElementById('aq-container'))return;if(aqi>=AQ.length){sAQ();return;}var q=shuffleQ(AQ[aqi]);document.getElementById('aq-prog').style.width=(aqi/AQ.length*100)+'%';document.getElementById('aq-container').innerHTML='<div class="ex-card"><div class="ex-num">Question '+(aqi+1)+' of '+AQ.length+(q.tag?' &middot; <span style="color:var(--ac);">'+q.tag+'</span>':'')+'</div><div class="ex-q">'+q.q+'</div><div id="aq-opts">'+q.opts.map(function(o,i){return '<button class="ex-opt" onclick="aAQ('+i+')">'+o+'</button>';}).join('')+'</div><div class="ex-feedback" id="aq-fb"></div><div><button class="btn btn-primary btn-sm" id="aq-next" style="display:none;margin-top:14px;background:var(--ac);" onclick="nAQ()">Next &rarr;</button></div></div>';aqd=false;}
function aAQ(i){if(aqd)return;aqd=true;var q=AQ[aqi];document.querySelectorAll('#aq-opts .ex-opt').forEach(function(b,j){b.disabled=true;if(j===q.ans)b.classList.add('correct-ans');else if(j===i&&i!==q.ans)b.classList.add('wrong-ans');});if(i===q.ans)aqs++;var fb=document.getElementById('aq-fb');fb.innerHTML=q.fb;fb.className='ex-feedback show '+(i===q.ans?'fb-correct':'fb-wrong');document.getElementById('aq-next').style.display='inline-block';}
function nAQ(){aqi++;rAQ();}
function sAQ(){document.getElementById('aq-prog').style.width='100%';document.getElementById('aq-container').style.display='none';var pct=Math.round(aqs/AQ.length*100);var el=document.getElementById('aq-score');el.style.display='block';el.innerHTML='<div class="score-big">'+pct+'%</div><div class="score-sub">'+aqs+'/'+AQ.length+' correct</div><p style="font-size:14px;color:var(--text-2);margin:12px 0 20px;">'+(pct>=80?'Solid. You can name the concepts and apply them.':'Worth another pass through the Concepts tab and the week page.')+'</p><button class="btn btn-primary" style="background:var(--ac);" onclick="reAQ()">Retry</button>';}
function reAQ(){aqi=0;aqs=0;document.getElementById('aq-container').style.display='block';document.getElementById('aq-score').style.display='none';rAQ();}
function initWorkshop(){initTasks();rAQ();}
